#!/usr/bin/env python

import sys

from rqt_postproc.postproc_module import PostProcPlugin
from rqt_gui.main import Main

plugin = 'rqt_postproc'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
