# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from object_list/Classification.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Classification(genpy.Message):
  _md5sum = "37b53ddc70d71a526ada035ab3f28e33"
  _type = "object_list/Classification"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float32 car
float32 truck
float32 motorcycle
float32 bicycle
float32 pedestrian
float32 stacionary
float32 other
"""
  __slots__ = ['car','truck','motorcycle','bicycle','pedestrian','stacionary','other']
  _slot_types = ['float32','float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       car,truck,motorcycle,bicycle,pedestrian,stacionary,other

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Classification, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.car is None:
        self.car = 0.
      if self.truck is None:
        self.truck = 0.
      if self.motorcycle is None:
        self.motorcycle = 0.
      if self.bicycle is None:
        self.bicycle = 0.
      if self.pedestrian is None:
        self.pedestrian = 0.
      if self.stacionary is None:
        self.stacionary = 0.
      if self.other is None:
        self.other = 0.
    else:
      self.car = 0.
      self.truck = 0.
      self.motorcycle = 0.
      self.bicycle = 0.
      self.pedestrian = 0.
      self.stacionary = 0.
      self.other = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_7f().pack(_x.car, _x.truck, _x.motorcycle, _x.bicycle, _x.pedestrian, _x.stacionary, _x.other))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 28
      (_x.car, _x.truck, _x.motorcycle, _x.bicycle, _x.pedestrian, _x.stacionary, _x.other,) = _get_struct_7f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_7f().pack(_x.car, _x.truck, _x.motorcycle, _x.bicycle, _x.pedestrian, _x.stacionary, _x.other))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 28
      (_x.car, _x.truck, _x.motorcycle, _x.bicycle, _x.pedestrian, _x.stacionary, _x.other,) = _get_struct_7f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_7f = None
def _get_struct_7f():
    global _struct_7f
    if _struct_7f is None:
        _struct_7f = struct.Struct("<7f")
    return _struct_7f
