# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from object_list/Features.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Features(genpy.Message):
  _md5sum = "acfb5ca82687e271a6722833317ebf1a"
  _type = "object_list/Features"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """uint8 FL
uint8 FM
uint8 FR
uint8 MR
uint8 RR
uint8 RM
uint8 RL
uint8 ML
"""
  __slots__ = ['FL','FM','FR','MR','RR','RM','RL','ML']
  _slot_types = ['uint8','uint8','uint8','uint8','uint8','uint8','uint8','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       FL,FM,FR,MR,RR,RM,RL,ML

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Features, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.FL is None:
        self.FL = 0
      if self.FM is None:
        self.FM = 0
      if self.FR is None:
        self.FR = 0
      if self.MR is None:
        self.MR = 0
      if self.RR is None:
        self.RR = 0
      if self.RM is None:
        self.RM = 0
      if self.RL is None:
        self.RL = 0
      if self.ML is None:
        self.ML = 0
    else:
      self.FL = 0
      self.FM = 0
      self.FR = 0
      self.MR = 0
      self.RR = 0
      self.RM = 0
      self.RL = 0
      self.ML = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_8B().pack(_x.FL, _x.FM, _x.FR, _x.MR, _x.RR, _x.RM, _x.RL, _x.ML))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 8
      (_x.FL, _x.FM, _x.FR, _x.MR, _x.RR, _x.RM, _x.RL, _x.ML,) = _get_struct_8B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_8B().pack(_x.FL, _x.FM, _x.FR, _x.MR, _x.RR, _x.RM, _x.RL, _x.ML))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 8
      (_x.FL, _x.FM, _x.FR, _x.MR, _x.RR, _x.RM, _x.RL, _x.ML,) = _get_struct_8B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_8B = None
def _get_struct_8B():
    global _struct_8B
    if _struct_8B is None:
        _struct_8B = struct.Struct("<8B")
    return _struct_8B
